CREATE TABLE "barang" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nama_barang" varchar,
  "harga" int,
  "stok" int,
  "kategori_id" int,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "kategori_barang" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nama_kategori" varchar,
  "created_at" timestamp,
  "updated_at" timestamp
);

ALTER TABLE "kategori_barang" ADD FOREIGN KEY ("id") REFERENCES "barang" ("kategori_id");